name: 'AWS AssumeRole action in JavaScript'
description: 'Run "aws sts assume-role" and set environment variables'
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  role_arn:
    description: 'The Amazon Resource Name (ARN) of the role to assume.'
    required: true
  role_session_name:
    description: 'An identifier for the assumed role session.'
    required: true
  region:
    description: 'The region to use. Overrides config/env settings.'
    required: false
  duration-seconds:
    description: 'The duration, in seconds, of the role session.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
