name: assume-role
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: chrislennon/action-aws-cli@v1.1
    - uses: ./
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        role_arn: arn:aws:iam::217080158438:role/sts-test-role
        role_session_name: sts-test-session
        duration_seconds: 900
    - run: |
        aws sts get-caller-identity
